### ISSUE TITLE
Sync possiblity lists and writing systems in CrdtMerge

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#1173]
CrdtFwdataProjectSyncService.Sync does not currently sync any possibilty lists or writing systems, there is code in place to create/update/delete those things, but it's not being synced. 

Before implementing this sync I would like to have a test that detects data that was not synced.

**Comment by rmunn** [comment]
Comment copied over from #1178:

First step is to write test code to compare the available possibility lists from one project to those of another project. Run the sync, then use that comparison method to make sure everything from A got into B.

Second step is to implement the list syncing, so that the test goes green. ✅

**Comment by rmunn** [comment]
PR #1203 handles parts of speech (#1178). I'll implement semantic domains later in a different PR.
