### ISSUE TITLE
Users can create new project

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#16]
Users should be able to create their own projects.

- [ ] Determine how to build the project code
- [ ] What's the retention policy restrictions. Only admins can set as verified?

It should be split into 2 different actions, one to create a FLEx project, and one for other types of projects.

**Comment by rmunn** [comment]
Part of the process of creating a new project will be creating a new hg repo. There are three ways we could do that:

- Current way we're doing it: the API server has access to the hg-repos volume and copies an empty repo into the right place.
- The https://github.com/j3hyde/hgwebinit extension to hgweb allows creating new repos when a `push` is done to a non-existent location by a user authorized to create projects
- `hg init` can take a `ssh://` URL, so we could set up an SSH key in the hgweb container and have the API server run `hg init ssh://hg/path/to/new/project`.

My preference is for the SSH option, as the hgwebinit project hasn't been touched in 11 years and may or may not work with modern versions of Mercurial. The current way we're doing it requires the hg containers to live in the same pod as the lexbox API backend so that they can share a volume (ReadWriteMany volumes are possible, but get tricky when you're doing local k8s development). We probably want to move the hg containers out of the lexbox pod, so using `hg init ssh://` is probably the way to go here.
