### ISSUE TITLE
Show pre existing projects to users when creating a new project

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#253]
we want to help users discover existing projects when they are on the project creation page.
We will need to take into account sensitivity of projects because this would allow any user to essentially lookup projects they aren't apart of. We would then let them request an invite to collaborate on that project.

- Admins can use this as soon as its out (How **do** our admins currently find "related" projects? Probably by searching by language code? We should ask them.)
- We only show projects that are explicitly non-confidential
- Can we show vague metrics for projects for which we have no explicit (non-)confidentiality? e.g. "3 projects might be related" (Chris: We don't tell users how we determine that)
- What can a user do if they're shown a potentially related non-confidential project? Send a message? see #258 

- We're adding this:
  - Because we care about the quality of our "project library"
  - To encourage collaboration / minimize duplicate work
  - To automate what our admins already try to do

**Comment by rmunn** [comment]
Now that #952 is merged, it should be possible to start implementing this.

**Comment by rmunn** [comment]
We now have, in FLExProjectMetadata, lists of vernacular language codes. We can use that to perform a search. The rules will be:

* Project must belong to an org that the user belongs to (waived for site admins)
* Project must have `isConfidential: false` (waived for site admins and org admins)
* Project must have at least one vernacular language with language code same as the one just entered on new project page

How do we check for vernacular languages? A good-enough search for language `xyz` would be that we look for any code that matches one of the following rules:

* Is exactly `xyz`
* Is exactly `qaa-x-xyz` (SIL standard for languages that SIL has assigned a code to, but that aren't yet in the ISO 639 registry)
* Starts with `xyz-`

This search should be triggered when the language code is 3 letters, or the language code is 2 letters and is a valid 2-letter code. Also, before doing the search, we'd likely need to convert 3-letter codes to their 2-letter equivalent, if any, because the writing system tags in FLEx projects are stored as `en` rather than `eng`, `fr` rather than `fra`, and so on. We may want to store the list of valid 2-letter codes in the database so it can be queried quickly, either that or hardcode it in code; there are 190 valid codes (183 current and 7 deprecated) so it wouldn't be too large of a C# file.

**Comment by rmunn** [comment]
From discussion with Kevin, we might also want to search by project name similarity. That will be a separate GraphQL query.

**Comment by rmunn** [comment]
This is now blocked until #986 is completed; see https://github.com/sillsdev/languageforge-lexbox/issues/258#issuecomment-2262115615 for details.
