### ISSUE TITLE
let users request to join a project in their org

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#258]
users might find out that a project already exists at the project creation page. Users should be able to request to join any project that is in their org.

maybe depends on #576
depends on #254

**Comment by hahn-kev** [comment]
related to #253

**Comment by rmunn** [comment]
This will be fixed by #979, but when Kevin and I discussed the design, we decided to use the new feature of the AddProjectMember modal where it can take a user ID, and have the URL to approve the project join request simply be the project page, with URL parameters that will pull up and populate the AddProjectMember modal. That does mean, however, that this issue is now blocked behind the completion of #986, which is where that feature is being added.

So I'm marking this issue as Blocked for now, and moving on to work on something else until #986 is finished (which should be pretty soon).
