### ISSUE TITLE
HTTP 413 Request Too Large when doing `hg push` of sena-3 project

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#310]
To reproduce:

- Start up the local dev k8s setup
- Go to the Sena-3 project
- Reset the project (downloading the .zip file somewhere first)
- Unzip the .zip file into a `local-sena-3` folder
- `cd local-sena-3`
- `hg push http://admin@localhost/hg/sena-3`
- Type in the admin password
- Mercurial fails with HTTP 413 error

I believe the 413 is coming from the NGINX ingress controller, and https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#custom-max-body-size is the setting we'll need to tweak for the `/hg` path so that larger POSTs are allowed (hg does a single HTTP POST with the entire bundle, which in Sena-3's case is 64628034 bytes = 61.634096146 MiB.

Note that this is unlikely to happen often, but will most often happen when an admin is trying to reset the Mercurial history of a project and so is trying to push a single commit containing the entire project.

**Comment by hahn-kev** [comment]
it turns out this is a [Cloudflare limitation](https://developers.cloudflare.com/workers/platform/limits#request-limits), which isn't surprising.

**Comment by myieye** [comment]
I know this is a very long stretch, but just throwing it out there:

I just discovered that there's a very mature and standardized protocol + implementations for resumable/chunked uploads called [tus](https://tus.io/). It sounds so mature that I would have expected to find a premade proxy for large web-requests, but I can't. However, I get the impression that it wouldn't be too hard to make one. We wouldn't be using it for its resumable feature (although that's primarily how it's branded) just for it's chunking.

If we went that route we'd:
1) put a tus proxy in front of cloudflare for our hg domains that feeds the push to a tus server in chunks 
2) add a [.NET tus server](https://github.com/tusdotnet/tusdotnet) to our cluster for receiving pushes and then ultimately pushing to the real project repo before finally telling the tus client to tell Chorus that the request is done

Yeah...I put it out there primarily, because I was positively suprised by the maturity of tus. So, the proxy wouldn't feel too much like a dirty hack.

**Comment by hahn-kev** [comment]
Yeah I thought about this, it may be simpler to improve the resumable protocol, but I don't really want to put work into any of that since we're trying to get away from mercurial all together. Thoughts? Maybe it would be worth it to improve resumable.

**Comment by hahn-kev** [comment]
to solve this we're going to do a couple things. We're going to tell users to use resumable if they run into this problem. For admins doing a project reset we're going to change the design of that so that we can avoid the problem of a large hg push.

depends on #327

**Comment by rmunn** [comment]
Our Cloudflare limit appears to be [200 MiB for HTTP POST](https://github.com/sillsdev/languageforge-lexbox/issues/327#issuecomment-1765656913), not 100 MiB as I previously thought. So I think it's unlikely that users will run into this limit in normal usage, and the use case of admins pushing a project after a reset should be taken care of by #327.
