### ISSUE TITLE
Run node playwright tests as part of integration testing

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#346]
This will give us more visibility into flakiness and failure patterns etc.

**Comment by rmunn** [comment]
What is the intent of this issue? I could see two possibilities:

1. Run the Playwright tests as part of each PR, or
2. Switch `.github/workflows/integration-tests.yaml` to run Playwright tests in Node rather than in .NET

The original title, "Run Playwright and other integration tests separately in CI", makes me think option 1 is what was intended. But yesterday's title change to "Run node playwright tests as part of integration testing" makes me think the intent is now option 2, rather than option 1.

So... are we wanting to run Playwright tests for every PR? Or are we abandoning that idea and just modifying the existing `.github/workflows/integration-test.yaml` to run the Playwright tests under Node rather than under .NET? Or is it both: edit `integration-test.yaml` to run Playwright under Node when we run integration tests, but also run Playwright tests on every PR as well?

The work I've done so far on #671 is assuming option 2. If we actually want the Playwright tests running for every PR, then I'll get working on implementing option 1 as well.

**Comment by myieye** [comment]
We certainly want to start running integration tests against develp after new deployments, but that's not what this issue is about.

It was originally about running Playwright tests in a different step/job than the other integration tests so that we had a better overview. Running Playwright tests in Node forces us to do that anyway 👍.
