### ISSUE TITLE
error Unexpected end of JSON input

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#397]
there's a whole bunch of traces in our logs with that error, here's an example
https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-sveltekit-client/result/xA8qXQ1BWPh/trace/g9hxXteCjES?fields[]=s_name&fields[]=s_serviceName&span=949d9f7f3d33dd6b

**Comment by hahn-kev** [comment]
@myieye would you look into this? It's throwing a bunch of errors into our tracing and I suspect it's from checkly since it's every 30 minutes. Looks like it has something to do with attempting to logout but it's hard to tell.

**Comment by myieye** [comment]
This looks like the relevant issue: https://github.com/sveltejs/kit/issues/10022

I.e. we're getting these errors, because:
- We have routes that don't have load functions
- SvelteKit seems to screw up a bit here and try to invalidate the data for these routes
- The invalidation requests land in our `[catch-all]` route, which just returns a 404
- The client-side invalidation code expects JSON 💥
