### ISSUE TITLE
Track Project Entry count

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#4]
We want to show users the number of entries in a project and the date it was last synced. We're not sure how to achieve that right now.

- [ ] How do we determine the entry count for a given project?
- [ ] When do we record a sync for a project, we could easily get false positives for failed logins for example.

**Comment by hahn-kev** [comment]
What trigger's a refresh of the data.
ideas:
- nightly sync
- manual sync with a button
- auto sync after S&R (already implemented)
- background auto sync when you view the project page.

**Comment by hahn-kev** [comment]
this issue is only about entry count now

**Comment by rmunn** [comment]
One way to quickly determine the entry count for a FLEx project would be to make a temporary `hg clone` of the project (fast if done on the hgweb container because hg clone uses hardlinks as long as the clone is on the same filesystem as the original, making it nearly instant). Then run `hg update tip` in the temporary copy and then count the occurrences of `<LexEntry` in the `Lexicon_*.lexdb` files, e.g.:

```
grep '<LexEntry' Linguistics/Lexicon/Lexicon_*.lexdb | wc -l
```

No XML parsing needed. Alternately, use `grep -ch` to get a count (`-h` suppresses printing the filename) and then add the ten resulting numbers together:

```
grep -ch '<LexEntry' Linguistics/Lexicon/Lexicon_*.lexdb | awk '{sum += $1} END {print sum}'
```

That would be even faster because `grep` would know it doesn't need to print out the actual occurrences of the matching text, so it can use an optimized code path that doesn't keep matches around. We'd need to check whether `awk` is available in the image, otherwise we can just retrieve all ten counts and add then together in C# code.

**Comment by rmunn** [comment]
Found a better solution with no clone needed: use `hg cat -r rev filename`. You can pass it multiple filenames and it will display all of them one after the other, so the following will return the correct result:

```
hg cat --cwd $REPO_ROOT -r tip Linguistics/Lexicon/Lexicon_{01,02,03,04,05,06,07,08,09,10}.lexdb | grep -ch '<LexEntry'
```

That should work no matter what the current working directory of the process is. Note that if `$REPO_ROOT` doesn't exist, `hg cat` will print "abort: No such file or directory: 'test-rmunn-04'" on stderr and exit with exit code 1. The `grep` command will then run and output 0 on stdout, then the whole pipe will have an exit code of 1 at the end. So if we use this approach, we should be prepared to handle catching that error on stderr.
