### ISSUE TITLE
users may not be able to register on their own

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#501]
talking to a facilitator we got the following feedback, summary courtesy of Bard

**Challenge:**
* New users often lack computer experience.
* Facilitator creates user accounts for new projects (remotely, with only names).
* Users don't have email addresses yet, making self-registration difficult.

**Current solution:**
* Facilitator manually create accounts and assign generic passwords.
* Facilitators download software and projects for participants.
* Passwords are rarely used but needed for downloading on new devices.

**Advantages:**
* Saves time and avoids complications for new users.
* Easy password recovery using predictable usernames and shared password.

**Desired outcome:**
* Streamline onboarding for new users with minimal tech skills.
* Maintain centralized account management and security.

**Possible solutions:**
* Implement bulk user creation tools.
* Guest user accounts with very limited access allowing us to weaken guest account restrictions, use the create (or org) as the point of contact for those users.

**Comment by myieye** [comment]
The more I think about it, the more it seems to me that we can reuse the User role and simply need a:
- Created-by-admin flag (or the admin’s ID) that means: “this user is safe: they’re not impersonating an org member."
- When enabled, the user doesn’t need to verify their email/phone number in order to:
  - Be added to a project (By admins only (or only the admin that created them)? What’s the risk?)
  - Do Send/Receive

That preserves the benefits of the User system-role:
- Can take as much responsibility of their own account as they want (e.g. reset password)
- Can “promote” themselves (so they don’t ever create a second account) by adding and/or verifying an email/phone number, which then gives them permission to:
  - Request a project of their own

These are the key reasons I can think of regarding why we’d want users to verify their email and none of them apply if an admin creates the account and feels responsible for it:
- Users can't impersonate other users (e.g. hackers can't pretend they're SIL members, because they can't verify an SIL address)
- We force users to take more ownership of their account (e.g. we make sure they have the ability to reset their own password if necessary without requiring an admin's help)
- We have a way of contacting users if necessary (e.g. we contacted lots of users for various reasons when we migrated, trying our best to make it as painless as possible)
- We could add features like "magic links": instead of the user logging in with their password, they just enter their email and get an email with a link that logs them in automatically.

**Comment by rmunn** [comment]
Notes from design discussion with @hahn-kev -

- For now we won't allow bulk-created users (who don't have email addresses) to log in to the UI, only to Send/Receive
- We may revisit that later, but it's easier to open a door than close one
- UI design for first version of the feature: bulk-create is a multi-line textbox admins can paste into, split on newlines and trim spaces left and right to get list of usernames
    - Same password for each bulk account (in future we might auto-generated a simple alphanumberic pw)
    - Choose a project that the bulk users will be added to (REQUIRED)

**Comment by rmunn** [comment]
More discussion with @hahn-kev and @megahirt -

- Bulk-add button on project page (automatically selects project to add the users to)
- Project managers can invite by email. Two formats allowed: comma-separated (paste from the To: line of an email) or newline-separated
- Admins can do the bulk add by username only, assign passwords
- If username conflict, alraedy-existing users are listed in the UI after the fact. They're already added to the project, but the project manager (or admin) who added them is informed (and there's a "copy this list to the clipboard" button) so they can take action, like deciding which of those usernames belonged to someone else and shouldn't be added after all.

**Comment by rmunn** [comment]
Now that some user accounts won't have email addresses, EmailService needs to be able to handle that.

The design decision I made is that if a user account without an email address somehow gets SendForgotPasswordEmail (or a few other email types) called on it, EmailService will quietly do nothing rather than throw an exception. If we decide we'd rather throw an exception, I can of course change that decision.
