### ISSUE TITLE
svelte client can create a lot of otel events

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#552]
in honeycomb we say a lot of events Feb 6th (twice the normal amount) that influx came from our local dev environment. Not sure who's machine. 

I suspect this is due to playwright test development work, but I can't tell from the traces.

Remediation steps:

- [ ] add a span attribute to indicate it's playwright related, or change the user agent used by playwright.
- [ ] create baggage to distribute that attribute to any/all spans
- [ ] add a span attribute to indicate the mac address in dev (of the dev machine if possible), failing that just a unique id for each dev so we can determine who's machine might have caused the issue.
- [ ] possibly filter out any playwright events on the otel collector when in local dev. Needs further research

**Comment by hahn-kev** [comment]
it looks like there can also be a bunch of click events from nowhere. I can launch local dev, go to the admin page (seems worse than home), wait for everything to settle, clear the network tab. Click in an empty space on the page and I'm seeing 13 traces for that single click event. When I do the same thing in production there's over 100, I'm guessing it must be related to the number of elements on the page or something but I have no idea.

**Comment by myieye** [comment]
Figured out the click events. It's our overlay.
- We never remove global click handlers for closing overlays :scream:
- Apparently OTEL doesn't use it's own click handler, it just instruments all click handlers. That kind of makes sense I guess... :thinking_face:
So:
- I think we should still just turn off click-tracing. It's never added value for us.
- I can use the current madness to make sure I start handling click handlers properly :smile:

**Comment by myieye** [comment]
So we get 20M Honeycomb "events"

> ## [What is an event when it comes to trace data?](https://www.honeycomb.io/pricing#que_6_2)
> Traces are comprised of multiple spans. Each **_span in a trace_** is counted as one event by Honeycomb. Each **_SpanEvent_** and each Link (in [OpenTelemetry](https://docs.honeycomb.io/getting-data-in/opentelemetry-overview/)) count as one event.

So, page loads seem to be what's killing us. Especially in dev, where resources tend to be served up as smaller individual pieces (I think).
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/2060f30d-47f5-4664-adf1-3456a6b81c9c)

For every resource of every page load there's a bunch of span-events, so it's 1 GET + (N Resources * M Events):
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6fd54b74-5fb4-4ccb-b762-99001368d870)

A page load can have a lot of spans (e.g. 240), so we're looking at 240 * 9 = 2160 events for some page loads:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/fccae8ab-871c-4800-bb80-a04296830bfe)

The count for GET is higher, because it's not only for page-loads. In fact, I bet our http-instrumentation is tracing the same resources as our document-load instrumentation. That would explain why the number is similar, but higher:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/17ddbff2-da6b-4659-89e0-4ac69ef605ac)

I think the main purpose for document load is measuring performance, which isn't really interesting in dev, because it's not a "real" environment. An easy win would be to turn that instrumentation off in dev.

Some more interesting views:

Ordered by count:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/545baf36-20c3-4a16-948f-fc56d644359a)

Ordered by number of span-events:
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/0ae6d18b-1573-4260-971e-a59d566710ac)

Open questions:
- [ ] Do we turn off document-load globally? Only in dev? Under the assumption that http-instrumentation is probably covering most of that anyway, this sounds good? I've never dug into resource timings.
- [ ] Do we turn of click tracing? I think so.

**Comment by myieye** [comment]
To relate my findings to Playwright (what this issue is actually about), I don't think whether OTEL is turned on/off for Playwright is particularly relavant. I think we just need to decide what to do with document-load instrumentaton.

**Comment by myieye** [comment]
I split out the bad overlay event handling into #566
