### ISSUE TITLE
check on UpdatedDate fields

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#579]
some updatedDates may not be getting updated as expected. Check into them

- project updated
- user updated

**Comment by rmunn** [comment]
I wonder if we should be [using a DB trigger for the updated date column](https://www.postgresql.org/docs/current/contrib-spi.html#CONTRIB-SPI-MODDATETIME) (see [here](https://dba.stackexchange.com/questions/158743/postgresql-auto-update-updated-at-with-custom-column) for usage example) rather than doing it ourselves in the backend code? That way it would be guaranteed to fire on every DB update, and we wouldn't run the risk of forgetting to update it.

The only reason I can see why we'd want to keep this in the C# backend code, rather than in a database trigger, is if there are *some* DB updates that we would want to choose not to modify the UpdatedDate. E.g., when we run UpdateAllRepoCommitDates, do we want all of those updates to change the UpdatedDate of the project? Or do we only want the UpdatedDate to change when something non-metadata-ish has changed? I.e., when an admin runs UpdateProjectTypesForUnknownProjects, do we want to set the UpdatedDate?

For now, I'll proceed on the assumption that we want to be selective in when the UpdatedDate gets updated. Don't fire it on metadata-ish changes like setting the last known commit on a project that was not otherwise touched, and only update it when something meaningful changes (new project member added, Send/Receive happens, that sort of thing).
