### ISSUE TITLE
hgweb is very slow

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#646]
I think this is pretty serious...

hgweb takes approximately 30s for almost everything. I think that's the root cause of the [one](https://github.com/sillsdev/languageforge-lexbox/issues/644), [two](https://github.com/sillsdev/languageforge-lexbox/issues/645) new issues I just created.

I'd be willing to bet that it's, because we now have tons of repos and so hgweb takes a long time to scan them all.

**Comment by hahn-kev** [comment]
@tim-eves can we get faster disk access in prod? Are we accessing the volume over the network as it stands today? We're using the `weekly-snapshots-retain-4` for the volume in question.

**Comment by hahn-kev** [comment]
looking into this a bit more. It's also effecting S&R performance because after each push we update the last commit date which calls the hg json api. We should switch that code over to scheduling a job to avoid that issue.

**Comment by myieye** [comment]
It looks like I was wrong. In this graph we can see the performance deterioration and it does not line up with repository migration. @hahn-kev migrated the last 1000 projects on Feb. 20 and 21.

Max duration:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/0dfd3b92-3fa5-413f-89ab-2111c52854f1)

Avg duration: (doesn't look nearly as bad 😉)
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/6330528c-3b81-4c3d-9fe2-7c3ecbc8bd39)

Based on the graph, performance seems to have deteriorated twice recently:

**Febuary 27/28**
- The lesser of the two deteriorations.
- Does not line up with a release
- Triage: I don't know. Maybe it was just a bad couple of days 🙈 

**March 4/5**
- Looks pretty serious in the first graph
- Lines up with our latest release
- Triage: 


Note: it doesn't look like it's affecting resumable directly. After looking more closely at issue two linked above, everything has acceptable performance **except** reading the last commit date after finishing a push:

hg example:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/83fb8235-fefd-4823-a97a-2059e6f1bc7b)

resumable example:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/ee42480e-2906-42a7-98dc-6e4b21d37e3b)

**Comment by myieye** [comment]
There are 2 changes that I think ought to be mentioned:

- [Adding revision numbers](https://github.com/sillsdev/languageforge-lexbox/commit/168a27652b5e46e46f402b1db46f8d8a94b239be#diff-50f2894f8931125449eb5d1620cdfe663b86b243fa32233bb22e6a6de7ab050a) to our hg log json format

I don't think this can be the cause. Otherwise only log requests would be affected.

- [Setting the hgweb refresh interval](https://github.com/sillsdev/languageforge-lexbox/commit/157b420e02bd17d6588e2a045abe1f6904517e58#diff-5813f337c086e37cb93b06bb5f5790709f5ef87b4359f7e11cb16ba846476f03) from 20 to 5

If this is the cause, I wouldn't have expected max(duration_ms) to increase, but it did.

Note: Our release notes claim that this commit was released on Feb 14, but I think that's a mistake. It's in the commit immediately after the commit that triggered the release:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/726c708c-cd56-436a-8e5b-5023c73d852f)
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/63b8bc3b-5194-414b-ac0b-f3a275c8f21d)

**Comment by megahirt** [comment]
There is also the somewhat remote possibility that it's coincidental that server performance degradation coincides with the latest release and there is another external cause (we should talk with LTOps).

**Comment by myieye** [comment]
(I didn't get the dates quite right, but anyway...)

It was actually about seven hours after our release that the problem started 🤔
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/f3456827-037f-457d-9bd2-a361ae140130)

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/ad41af64-47c1-452f-bd61-3c36831eb3d4)

**Comment by megahirt** [comment]
yeah, I guess the only way to know for sure is to rollback the commit and see if there is an improvement

**Comment by myieye** [comment]
For the record, if we were to decide to explicitly list all repos in hgweb.hgrc instead of using a path with a wildcard (and thereby not need hg to ever refresh itself), the cleanest way to update the list would probably be with [this extension](https://wiki.mercurial-scm.org/HgcfgExtension).

**Comment by hahn-kev** [comment]
looks 

> There is also the somewhat remote possibility that it's coincidental that server performance degradation coincides with the latest release and there is another external cause (we should talk with LTOps).

I'm wondering if it could be this. Because yesterday I changed the refresh time to 30s and looking at the graphs I don't see any change. As Tim said adding the rev to the json format would not effect all queries so I doubt that's the cause.

Another option is that this issue is caused by a single project and a user pushed something at the start of this issue. Otherwise it's not clear why the performance would degrade 7 hours after the release, it should be right away. Maybe there's a really big project?

Here's the query I'm working with, I've saved it to the perf board. https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/SjJEYtnHFC?preferOverlaidCharts

**Comment by hahn-kev** [comment]
Here's our proof of when thing started to go bad compared to the version. I grouped by `service.version` yellow is the 02-14 version, purple is the 03-04 version. You can see the March version was fine for a bit until it went bad.
![image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/ff458b8a-dc9f-4933-8a3d-0d3b66602d2b)

**Comment by hahn-kev** [comment]
Doing some more investigation it looks like only capabilities and our log requests have gotten worse, looking here:
https://ui.honeycomb.io/sil-language-forge/environments/prod/datasets/lexbox-api/result/DbVtUNWg9cN
This is grouping requests by query and it looks like only those 2 have gone up and others are fine.

**Comment by hahn-kev** [comment]
We should figure out the root cause, but I do think we could cache capability requests in dotnet to relieve pressure on the server.

**Comment by rmunn** [comment]
Looking through the Mercurial source, capabilities are definitely cacheable: they only vary when you change the Mercurial version or when you set certain Mercurial config options like `experimental.bundle2-advertise`.

**Comment by rmunn** [comment]
I'm becoming convinced that our `changesets` query is at fault. As I was looking through the Mercurial code, I found that the `changelistentry` function compiles a dictionary of all the data a template *might* want, not just the data the template actually requests. Among that data is:

```python
    files = listfilediffs(ctx.files(), n, web.maxfiles)
```

The default value of `web.maxfiles` is 10. Which means that every time we load a project's changesets to render the train-tracks graph, Mercurial is loading file diffs for 10 files for every changeset, even though we don't need that data. That's tons of unnecessary work we're asking it to do. Thankfully Mercurial defaults to just loading 10 changesets when you ask it for a log, otherwise it would be doing this work all the way back to the beginning of the repo.

**Solution:** we should set `web.maxfiles` to 0 in our hgweb config. I bet that will go a long way towards relieving pressure on the hgweb server. (I ran `top` on the hgweb server and loaded a project page, and watched the CPU usage spike at 26% before it eventually finished churning all the file diff data that we didn't need and didn't want).

**Comment by rmunn** [comment]
I'm unable to get to Kubernetes in staging right now (DNS timeouts looking up the Rancher control server on the staging VPN) so I can't test whether `web.maxfiles` is doing anything. I'm able to do it locally, but my dev computer is speedy enough I'm not noticing a difference (our test repos load in under a second, vs the 30+ seconds that we've been experiencing loading certain repos in production).

**Comment by rmunn** [comment]
Okay, reading further in the Mercurial code I see that `listfilediffs` is taking a list of files changed by the changeset and running each one through the `filedifflink` template, which just generates an `<a href="something">`. So the diffs aren't actually being calculated when you retrieve a log, and therefore changing `web.maxfiles` doesn't make a big difference to how much work the hgweb container has to do.

**Comment by rmunn** [comment]
> Here are the changes that I think ought to be mentioned:
> 
> [Setting the hgweb refresh interval](https://github.com/sillsdev/languageforge-lexbox/commit/157b420e02bd17d6588e2a045abe1f6904517e58#diff-5813f337c086e37cb93b06bb5f5790709f5ef87b4359f7e11cb16ba846476f03) from 20 to 5
> 
> If this is the cause, I wouldn't have expected max(duration_ms) to increase, but it did. This is still the mostly likely candidate of the ones I can find.

We probably should only set that to 5 on dev machines, and set it to 30 (up from 20) in both staging and production. Then the reset-project integration test, that sleeps for 5 seconds in a couple of places to ensure there's no race condition on the server, can be configured to sleep for a number of seconds determined by an environment variable, and we set that to 5 in dev and 30 in staging. If that one test takes an extra minute to complete on staging, well, we can pay that cost. Better that than overload the production hgweb instance.

**Comment by rmunn** [comment]
> For the record, if we were to decide to explicitly list all repos in hgweb.hgrc instead of using a path with a wildcard (and thereby not need hg to ever refresh itself), the cleanest way to update the list would probably be with [this extension](https://wiki.mercurial-scm.org/HgcfgExtension).

The Mercurial wiki links to https://bitbucket.org/bmearns/hgcfg/ for that extension, but that URL now returns a 404. https://github.com/fastcat/hgcfg claims to be a fork of that bitbucket repo. Its code is 11 years old, so we'll need to test it to make sure it still works (Mercurial's config format probably hasn't changed in the past decade, but it's quite possible that their extension API may have changed, likely due to the move from Python 2 to 3).

However, https://github.com/sillsdev/languageforge-lexbox/pull/652 may make this a moot point.
