### ISSUE TITLE
Decide how users with only a username should be added to more projects

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#649]
Currently only the Bulk Add/Create Members tool can be used to add users to a project using their username.

That means:
1) It's confusing that the simple "Add Member" doesn't work
2) It's only possible for admins to add them to a project

I think we either need to
1) make that information explicit somehow or
2) Change "Add Member"

I think (2) is the way to go.

**Comment by rmunn** [comment]
Yeah, the "Add Member" UI will need to change to allow usernames as well as email addresses. While we're changing its UI, it might be nice to have autocomplete the way Redmine did: you type "Rob" and you get people whose name is Robert, Robin, last name Robertson... Perhaps we don't show the autocomplete results to the user until there are 20 results or fewer, but that way they can save some typing time. (TBD: search on real names, but fill in username? Search on usernames only?)

Drawback: possible information exposure. If someone hostile manages to get credentialed as a project manager, they could use this to find out other people who have registered accounts.

For now, I'll just tackle making the Add Member UI allow usernames. The rule will be simple: if it has an @ in it it's an email address, otherwise it's a username. Autocomplete can wait until we have a chance to discuss it and decide if the information exposure possibility is a problem or not. But "Redmine used to allow autocomplete on people's names" does make for a compelling argument for including autocomplete in some form.
