### ISSUE TITLE
Can't filter projects by a user that has no email

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#673]
We currently use user's email address to filter projects. Now, some users don't have an email address.

I think we should do something like this:
- Rename the `ProjectFilters.userEmail` query-param to something...I don't know what
- Adapt the GQL query to search for a user who's email OR login matches
- Fix the current GQL email search from `icontains` to iequals (yes, it's been wrong for a while)
  - icontains is a custom implementation (See: CustomFilterOperations.cs). iequals will also need to be I think

**Comment by rmunn** [comment]
Why aren't we using the user ID to filter projects? I think that's a better solution than an `icontains` email search, and probably faster on the DB end as well.

Drawbacks: displaying the user ID would not be intuitive in the UI, and users would much prefer to see the user's name or email. So we'd need to change our Filter type (defined in FilterBar.svelte) to have a concept of an optional `displayValue`, different from the value. The value is what is sent to the API (e.g., a GUID) while the display value is what is shown to the user (e.g., a user's display name and/or email address).

**Comment by myieye** [comment]
Yes, the most correct way would certainly be to search by ID. I wouldn't fix this bug that way, because it doesn't seem worth the effort, but I think you can feel free to do so if you want.

**Comment by myieye** [comment]
But regarding your question: we used the email, because it's almost
equivalent to the user ID and it gave us a display value for free.

**Comment by rmunn** [comment]
The way I implemented this in https://github.com/sillsdev/languageforge-lexbox/pull/680 isn't ideal — I feel like there's a better way to handle getting the user display name — but it's worth considering. In my case, I didn't think adding a custom GraphQL operation was worth the effort, and I decided I'd rather invest the time in giving the filter a way to fetch the display name for display. (Since ProjectFilter.svelte shouldn't be needing to know anything about users, I gave it a function prop to be passed down from the parent. Another solution I just thought of, which might not be better, would be to let the query param value be "GUID,Display name", i.e. split the query param at the first comma. That doesn't feel quite right either.
