### ISSUE TITLE
Provide admins with autocomplete when adding a single user to a project

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#685]
Multiple admins have told me that it used to be easier to add users to a project, because they only had to start typing the user's name and then they could select the user from search results. (I'd have to research Redmin's capabilities to know exactly what that means.)

I think this was even possible when doing a bulk add (though from one admin it sounded like that feature maybe disappeared from Redmine at some point 😕.

As a first step, this issue is only about the "Add/Invite [Single] Member" feature.

Either we only do an autocomplete on the email or login the admin is typing, or we even match on the user's full name. The latter would be extra nice. Then the admin selects the user from the result and we put their email or login in the text box.

**Comment by rmunn** [comment]
I mentioned some issues with information exposure in https://github.com/sillsdev/languageforge-lexbox/issues/649#issuecomment-2017151313, but that was for project managers. If the user is an admin, then autocomplete doesn't present any information-exposure issues: admins can already see everything.

**Comment by rmunn** [comment]
As for the Redmine feature, you would type the first few letters of the user's name (the display name), and it would present a results box with checkboxes. You could then, in theory, add multiple users to the project at once, though in practice since it was autocompleting on their name, you wouldn't be adding more than one user at a time unless two people had the same name. (Maybe adding a husband-and-wife team to the same project by searching on last name, but that would be rare).

**Comment by megahirt** [comment]
I agree with @rmunn , adding autocomplete for admins would be a plus.  Let's not leak user existence for non-admins
