### ISSUE TITLE
detect empty project and change "Get project" instructions

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#686]
right now when we show instructions to get a project they're assuming the project already has data in it, but that might not be the case and is very confusing when the project is empty.

We should be able to use the fact that last commit date is null to determine if a project is empty or not. Then we can change the instructions we give to a user to interact with the project in FLEx or the client app.

ignore the issue transfer, I added it to the wrong repo from the project page.

**Comment by rmunn** [comment]
Admin request from #688, copied over here because I've closed #688 as a duplicate:

> I had a guy uploading a project to Language Depot.  He had trouble because he was using the instructions under the button to ‘Get Project’, which of course didn’t work.  He wanted to change those instructions, which would be wrong, but what do you think about a new button next to ‘Create Project’ that was titled something like ‘Upload new project’.  The steps he suggested are:
> 
> 1. Download FLEx onto your computer.
> 2. Open the FLEx application and select "Create a new project...".
> 3. Fill in the required information: name of project, name for the folder (e.g. "Saluan-LOI"), etc. Then click "Finish".
> 4. After the new project opens, click on "Send/Receive\Send this Project for the first time".
> 5. Click on "OK (I have the master project)".
> 6. Click on "Settings..." and enter your LanguageDepot login credentials.
> 7. Click Log in, then select the Project ID from the drop-down menu.
> 8. Click on Internet. This will initiate the first Send/Receive.
> 
> Just passing this along.  It is documented elsewhere, but…

**Comment by rmunn** [comment]
The FLEx Send/Receive instructions are [here](https://software.sil.org/fieldworks/support/using-sendreceive/). They are rather wordy, because they're trying to cover all use cases (ChorusHub, Language Depot, collaboration with WeSay or just with FLEx, etc) in one document. Since that's a lot to ask users to read, I'm inclined to put a link to it near the bottom of the instructions but let the instructions be complete (and as short as reasonably possible) without anyone needing to click through to read the rest.

**Comment by rmunn** [comment]
We can't necessarily rely on the last commit date being null to detect an empty project, because we don't clear it after a project reset. From the dev server:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/90762/2d6cc74d-c7bd-425d-9499-d52bad5473f4)

However, the last commit date is reliable 98% of the time. So perhaps the logic could be:

1. Set bool value `isEmpty` to `lastCommit == null` initially
2. Subscribe to the `changesetStore` and when it returns results, set `isEmpty` to `changesets.length == 0`

That way most of the time there won't even be a flicker of change, and in the rare case where a project has been reset and not populated yet, so that `isEmpty` initially has the wrong value, it should get set correctly before the user has had time to move the mouse cursor to the "Get Project" button and see the instructions.

**Comment by myieye** [comment]
> We can't necessarily rely on the last commit date being null to detect an empty project, because we don't clear it after a project reset.

That sounds like a bug. We should:
- Delete project metadata when we reset a project
- Update project metadata when we finishing reseting a project with a replacement zip (we do some of this)
Maybe you can fix those ☝️  in this PR or a seperate bug?

**Comment by megahirt** [comment]
yeah.  either fix the bug in this PR, or assume that commit date is 100% reliable and fix the bug in a separate PR.  Thanks guys!

**Comment by myieye** [comment]
By the way, I've created an issue for the bug that should cover this #728
