### ISSUE TITLE
Research options for improving hg[web] performace

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#693]
Ideas we want to pursue:
- [ ] Faster volume
- [ ] FS performance metrics
- [ ] Research the cost of managing our own AWS/Digital Ocean/etc. cluster (our current TechOps cost: ~$200)

Other ideas mentioned:
- Migrate to git
- Cleanup dead repos
- Test performance in parallel AWS environment
- Make it disappear? 😁

**Comment by hahn-kev** [comment]
This image tells an interesting story. The results are sorted by the sum of time spent on each type of request in the last 7 days
![image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/38af1191-e35a-41e9-b138-638a44d9a6d0)

Put another way, this is a pie chart of the sum of time spent.
![Picture1](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/28a8ddb6-6e4c-4ffe-b8a9-c2b60649b77d)

Basically hgweb is spending over 50% of it's time responding to capabilities requests. It spends around %90 of it's time responding to capabilities and our commit log requests. We can fix this.

## capabliites
I'm fairly certain we can just cache this across all projects. If we really wanted we could just hard code the response, but I think it makes more sense to just cache it for 24hrs.
- [ ] cache capabilities requests

## hg log
Right now we're using the json api that hgweb provides because it's convenient, but I think we should shift that over to the command server and it may perform better. That would require some testing. We can use `hg log -T json` to get json output from the CLI, so we don't even need to parse the hg log output manually which is a huge win.
- [ ] use command runner instead of hgweb for hg log requests

**Comment by myieye** [comment]
But, if the capabilities request is slow, because hgweb is refreshing it's lost of repos, then caching that request will result in the next request being slow. I think capabilities is slow, because it happens to be the first request in a send/receive.

Maybe that theory needs to be tested. But, I think we ultimately need to solve the refresh performance problem.

Perhaps it's worth mentioning this again: we could maintain an exhaustive list of repos instead of using a wildcard in our hgweb paths config.

I love the idea of using our command runner to get change sets for the UI.

**Comment by myieye** [comment]
😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲 😲

**Comment by myieye** [comment]
Wow, just look at that long mysterious story of performance sorrows that unexpectedly ended with cheers of joy:

![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/b03d9355-7bf4-4dd6-ae56-53169a26ea31)

@hahn-kev Does anyone at TechOps know that we think they caused and fixed this for us?

**Comment by megahirt** [comment]
This could be one of those "we rebooted and things are better now"
situations.

Chris

**Comment by hahn-kev** [comment]
we recently deployed a new version and the hg pod ended up on a different node, previously the node it was on was the same node that the volume was mounted on. We also saw a small performance regression
![Image](https://github.com/sillsdev/languageforge-lexbox/assets/4575355/8705ab62-3f7d-4b80-81f0-36acae225309)

**Comment by hahn-kev** [comment]
I think we can consider this issue fixed
