### ISSUE TITLE
GetLastCommitTimeFromHg after project reset sometimes => 404

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#728]
Our project-reset Playwright test has bumped into this a few times ([one](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8691503332/job/23834214869), [two](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8690986749/job/23832425204)).
I assume it's the ol' `refreshinterval` trouble.
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/a074e3b4-36c9-4b2a-b292-972300521159)

I'd say, we should:
- [ ] Hand this off to our `UpdateProjectMetadataJob` (for durability and so that entry count gets updated as well)
- ~[ ] Make the job retry a few times (e.g. intervals: 0s, 4s, 8s), because we just don't know how long we need to wait for hgweb~ EDIT: I think we'll hope that @rmunn's PR fixes this.
- [x] #756

([example trace](https://ui.honeycomb.io/sil-language-forge/environments/staging/result/iGWjmKLEbcs/trace/HDAW2y6dgSP?fields[]=s_name&fields[]=s_serviceName&span=635063bf36234d09))
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/8b8b226f-8134-4a00-b892-a1c364cca231)

**Comment by hahn-kev** [comment]
That's a really good point. I like the idea of using the job, I'm not sure we need to retry, I'd say we just delay the start of the job, maybe start it in 30s after it's queued, that's not something we've done yet but Quartz supports it.

**Comment by rmunn** [comment]
> Our project-reset Playwright test has bumped into this a few times ([one](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8691503332/job/23834214869), [two](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8690986749/job/23832425204)). I assume it's the ol' `refreshinterval` trouble. 

Where's the failure in those test logs? I see the 404 in the otel trace, but [one](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8691503332/job/23834214869) has a failure in CloneBigProject, and [two](https://github.com/sillsdev/languageforge-lexbox/actions/runs/8690986749/job/23832425204) shows no failures. Neither one is showing a failure on the SendReceiveAfterProjectReset test.

That's not to say there isn't a problem here, of course. I just looked at the FinishReset code and I can see some potential race conditions in there: there are places where we delete the repo, then re-create it from the zip file — and if the hgweb "scan for new repos" process happens to run in between those steps, it could return a 404 for that repo until the next time it runs. I suspect we could rearchitect the FinishReset code to eliminate or greatly reduce the window of opportunity for those race conditions.

**Comment by rmunn** [comment]
Here's the current FinishReset logic:

```cs
    public async Task FinishReset(string code, Stream zipFile)
    {
        using var archive = new ZipArchive(zipFile, ZipArchiveMode.Read);
        await DeleteRepo(code);
        var repoPath = PrefixRepoFilePath(code);
        var dir = Directory.CreateDirectory(repoPath);
        archive.ExtractToDirectory(repoPath);
```

The hgweb logic for scanning for repositories is simply to walk the specified directory tree and look for `.hg` directories. It does no checking of the contents *inside* the `.hg` directory, just whether there's a directory named `.hg` — that's really all it checks for. So to narrow the window for 404's, we should extract the archive to a temporary directory on the same filesystem as the repo, then *move* the old `.hg` directory away and move the new `.hg` directory into place. As long as you're moving a directory to another location on the same filesystem, in Linux a directory move is an atomic operation. So the only window for the race condition is in the microseconds between the old `.hg` being moved away and the new `.hg` being moved into place: if hgweb happens to scan for new repos during that time, then it will return a 404 for that repository. This is something that should happen approximately once in a blue moon.

I propose to rewrite the FinishReset logic to use Directory.Move instead of deleting the repo and recreating it, to minimize the amount of time when a repo would return a 404 from hgweb. (The ResetRepo logic is already using Directory.Move, so it already has a near-zero window of opportunity for the race condition... but it could still be improved a little: *first* copy the empty repo files into a temporary location, *then* move the old repo away and move the new empty repo into place.)

**Comment by myieye** [comment]
@rmunn Thanks very much for tackling this! 😻

Regarding not seeing the failures in the links I shared: the failures are hidden in the Playwright Integration test logs.
The Playwright tests are green, because (1) at the time they always got marked green (I think I fixed that 4bafbd103566481509166d9847947af857716a10) and (2) because the tests succeeded on a retry so they actually were green this time 😆.

I've realized that we need a test for this. I'm going to try to contribute one.

Also, I think we've both made an incorrect/uninformed assumption 😉:
- You're assuming that hgweb refreshes are triggered on a schedule. I don't think that's true. I think they're triggered when hgweb receives a request (and hasn't refreshed for `refreshinterval` seconds). So, I think it always refreshes in the scope/context of a request; not at random times.
- I'm assuming that this is due to the `refreshinterval`...although my current understanding of hgweb doesn't give a satisfying explanation for how a project "falls out" of hgweb's repo list during the reset process. You've explained that there are two short periods of time when there is no .hg folder. My understanding would be that _during one of these two gaps_ a **different request** would have to have triggered a refresh that causes the being-reset repo to be removed from hgweb's list

Anyway, we really need a good test(s) that proves things are working.

**Comment by hahn-kev** [comment]
What if we just figure out how to set the refresh interval to 0 for staging? 

The big downside of that would be that it would make staging different from production, so that would be a good reason not to make this change.

**Comment by rmunn** [comment]
>     * You're assuming that hgweb refreshes are triggered on a schedule. I don't think that's true. I think they're triggered when hgweb receives a request (and hasn't refreshed for `refreshinterval` seconds). So, I think it always refreshes in the scope/context of a request. But other requests/users could trigger a refresh of course, so regardless, they could happen at any time.

I just checked the hg source and you're correct. The `refresh(self)` method in `hgwebdir` contains this logic:

```python
# refreshinterval <= 0 means to always refresh.
if (
    refreshinterval > 0
    and self.lastrefresh + refreshinterval > time.time()
):
    return
```

And, of course, it sets `self.lastrefresh` to the current time at the end of the method. So `refreshinterval` is a throttle for how often hgweb will read the directory: on every request, or not.

**Comment by rmunn** [comment]
This suggests a way to speed up our tests: instead of running WaitForHgRefreshIntervalAsync and waiting 5 seconds each time, we could create a method that tries a given HTTP request expecting a non-404 response, and if it gets a 404, retries that request once per second until either it get a non-404 or RefreshInterval seconds have gone by (in the latter case it would throw an exception to fail the test). That would allow most tests to run to completion without waiting too long, but the tests that happen to run right after another test ran quickly might have to wait up to 5 seconds for their newly-created project to show up.

Or, yes, we could set refreshinterval to 0 on staging (we should certainly set it to 0 in local dev), but I don't want staging configuration to be too different from production lest we miss something important that way.

**Comment by myieye** [comment]
It's not fixed quite yet, so reopening to make sure it doesn't slip through the cracks.
