### ISSUE TITLE
mark email address with .. as invalid

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#764]
Example address: test@test..org
This will pass all our validation until we try to actually send an email, then it'll blow up. We should improve our front-end validation to catch this early.

**Comment by rmunn** [comment]
Make sure the validation only rejects `..` if it appears *after* the @, because pretty much anything is legal as an email address. Someone might, for example, use robin.munn@gmail.com when giving their email to legitimate places, but robin..munn@gmail.com when giving it to shady places that spam you. (Because gmail just strips dots, both of those will end up in the same mailbox).

**Comment by myieye** [comment]
A fix for this was already in the release Yesterday (#730).
Feel free to reopen.

This is prod:
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/b11afdba-ad64-413e-a9fd-9b396a87acb2)
![image](https://github.com/sillsdev/languageforge-lexbox/assets/12587509/52d567c7-77e4-492b-a7f4-0eb3da0010cd)

**Comment by hahn-kev** [comment]
nice! Thanks for checking on that, didn't realize it was already covered.
