### ISSUE TITLE
querying a large project with the lf classic api can use too much memory

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#771]
this is kinda 2 problems. First is that it would be great if dotnet would not get itself killed using more memory than is available, the second is that the api should consume less memory while executing the endpoint, this would mostly require sorting and paging in mongo instead of in memory.

**Comment by megahirt** [comment]
> the second is that the api should consume less memory while executing the endpoint, this would mostly require sorting and paging in mongo instead of in memory.

Agreed.  Sorting is a solved problem for major languages (can choose to do it in the database, server side or client side because those locales/sorting rules are implemented and understood) but for minority languages there are additional challenges.  This is a fine change to address the current needs of the system, but will need to be revisted/addressed again in the future to accommodate minority language sort rules.
