### ISSUE TITLE
Bulk-add existing users to an org

### ISSUE THREAD

**Issue by myieye** [sillsdev/languageforge-lexbox#778]
we would like org admins to be able to bulk add (not invite) existing users to their org. This will work very similarly to the bulk add to project (eg: large textbox, one email/username per line etc). However this feature will work for org admins, and it will not create any users. We will add a button to the org page to allow this functionality.

**Comment by hahn-kev** [comment]
Another idea of how we could ease this is that when an org admin adds a project to their org, they could automatically make all project members a member of the org also.

**Comment by rmunn** [comment]
I think I agree that the bulk-add users feature will be best initiated from the org page, rather than the admin dashboard. I'm trying to figure out what the UX would look like of initiating a bulk-add-users-to-org flow from the admin dashboard, and I can't see it. We select a group users, then click a "Bulk Add to Organization" button, then select the org from a dropdown? Feels a little weird.

Doing it from the org page, I can see it working like this:

- On org page, admins can see a bulk-add button.
- When they click it, they get a modal with a UserTable component.
    - Alternately, they could get taken to the admin dashboard with a `&bulkAddUsersToOrg=GUID` query param, but I think UserTable in a modal, not leaving the org page, makes a lot more sense
- UserTable already has filters built in, so you can search for everyone ending in example.org
- "Select All" checkbox in table header, of course
- Once one or more users are selected, click the Done button

One UI design question I haven't figured out yet is what if you do a filter, select some users, then do a different filter? Should the selected users be cleared, or should they be included even though they're not visible right now? I could see arguments both ways, e.g. you want to add everyone with an example.org *or* test.com email address. (Not writing down the actual domains I mean here, just to be cautious). Two passes through the bulk-add tool isn't too bad, but it might be nicer to be able to do a single pass. But it might also be confusing. Thoughts?

**Comment by hahn-kev** [comment]
After talking about it with the team, lets just do the same thing we did for project bulk add. Have a text box where users can paste in a list of email addresses.
