### ISSUE TITLE
implement global error tracing for gql errors on the frontend

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#85]
Currently errors are lost and not correctly reported to otel, we should fix that and implement better tracing from gql to otel.

**Comment by myieye** [comment]
This is a fairly old issue, so I'm not sure what the state of things was back then 😆.
I believe GQL errors are generally traced right now.

However, there is 1 thing I'm eager to improve in the scope of this issue:
We have no access to the trace-id for client-side GQL requests, because they're currently **only** handled by the fetch auto-instrumentation, which is a black-box. So, it's a bit of effort to dig these traces up in honeycomb. We should wrap requests in such a way that our error handler has access to the "real" trace-id and doesn't just create its own trace.

Server-side GQL requests are always in the scope of a client-request and so all of our server-side code always has a "legitimite" trace-id for (e.g.) putting in an error object/on an error page.
