### ISSUE TITLE
db-deployment.yaml doesn't contain rollingUpdate

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#884]
While researching https://github.com/sillsdev/languageforge-lexbox/issues/883, I was watching Kubernetes manage pods as I re-ran `task up`. And I noticed that every other pod except db was using a rolling update strategy (where the new pod deploys first, then the old pod goes away) but the db pod terminated the old pod *first*, then set up the new pod.

This is probably the cause of the errors I've seen often in my lexbox api logs:

      An error occurred while scanning for the next trigger to fire.
      Quartz.JobPersistenceException: Failed to obtain DB connection from data source 'default': System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known

      An error occurred while scanning for the next trigger to fire.
      Quartz.JobPersistenceException: Couldn't acquire next trigger: 57P01: terminating connection due to administrator command

I've also seen:

    fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
      => TraceId:e689146ff82d0b93556a7f38b5fb1954
      An error occurred using the connection to database 'lexbox' on server 'tcp://db:5432'.
    fail: Microsoft.Extensions.Hosting.Internal.Host[11]
      Hosting failed to start
      System.Net.Sockets.SocketException (00000005, 0xFFFDFFFF): Name or service not known

Eventually Kubernetes restarts the lexbox pod and it comes up, but due to #883, I've often had the `deploy/lexbox` deployment give up after 80 seconds, which results in `skaffold dev` quitting. And then I have to re-run `task up`, resulting in another long wait, and a gamble whether this time the lexbox pod will acquire its DB connection in time.

I had been assuming that the lack of rollingUpdate in db-deployment.yaml was on purpose, because only one Postgres DB can use the volume at a time. But just in case it's an accidental omission, I wanted to mention it.

**Comment by rmunn** [comment]
https://www.digitalocean.com/community/tutorials/how-to-deploy-postgres-to-kubernetes-cluster shows an example of running multiple Postgres pods using a ReadWriteMany volume claim, so I suspect there's no inherent reason why we couldn't do a rollingUpdate for db-deployment.yaml.

**Comment by hahn-kev** [comment]
yeah I'm not sure who wrote that digital ocean article, but everything I'm seeing online (though I can't find anything in the official docs) say that you can not have more than 1 instance of postgres accessing the data directory, if you do then you would corrupt the database as it's designed expecting exclusive access to the data directory. If you want to have multiple databases then you need to setup replication (which we don't need).

All that said, this is why we're not using rolling updates, otherwise during the update you would have 2 instances of the database up at the same time. Seeing as how this is only an issue in local dev I'm not going to make any changes on production. But we may be able to find a solution for local dev. Maybe we can exclude the database from skaffold as there's no reason to redeploy it on `up` because it's not changing.
