### ISSUE TITLE
Hostname for hgresume must contain "resumable"

### ISSUE THREAD

**Issue by rmunn** [sillsdev/languageforge-lexbox#93]
The Chorus code which uses Mercurial to talk to a repository includes this method:

```csharp
public static bool IsKnownResumableRepository(string uri)
{
    return uri.ToLower().Contains("hg-test.languageforge.org") || uri.ToLower().Contains("resumable");
}
```

To ensure that our Send/Receive tests will use the resumable protocol when needed, we'll need to ensure that the hgresume container is given a name that contains "resumable". I suggest "hgresumable".

It will also be necessary to add instructions in the README to tell developers to add this line to their local DNS resolver (e.g., `/etc/hosts` on Linux): "127.0.0.1 hgresumable". Then the Send/Receive test can be written to talk to `http://hgresumable:8034` and it will work. (If running inside a container, that might need to become port 80, which means the test might need to be written to try port 8034 first, and then fall back to port 80 if 8034 doesn't work, considering a success on either port to be an overall success).

**Comment by rmunn** [comment]
Note that the path to the cache inside the container must remain `/var/cache/hgresume`, since that's a path that's hardcoded into the `hgresume` code.

**Comment by hahn-kev** [comment]
ugh that's annoying. I wonder if we can make a PR to Chorus so that we can just tell it we want it to be resumable, at the same time we could simplify the passing of credentials which I saw you had trouble with.

On second thought, if that's checking the entire URI (not just domain or host), could we do something like this for the url: `localhost:8034/proj-code?resumable=true` the query parameter should be ignored on our end.... just a random thought.
