### ISSUE TITLE
guest users who add an email are still marked as created by admin

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#936]
this prevents them from accessing features like requesting a project

**Comment by rmunn** [comment]
One reason for tracking the "created by admin" record was to help with GDPR compliance, as we can tell who requested the user's account. If a user adds an email address (and validates it), do we then consider that they have consented to give us their PII and we therefore no longer need to track which admin created the account? If so, then it should be pretty easy to simply set `CreatedById = null` once their email address is verified. (We do want to want for the verification step to complete, otherwise users could give themselves a "self-promotion" by simply entering `fake@example.com` as an address).
