### ISSUE TITLE
users who register via google login still have to verify their email

### ISSUE THREAD

**Issue by hahn-kev** [sillsdev/languageforge-lexbox#943]
I'm not sure we need to require that, we know they own the email because google gave it to us

**Comment by rmunn** [comment]
I believe we already handle this. When you login with Google and aren't registered, you go to CompleteGoogleLogin and then get redirected to the `/register` page with, among other things, a JWT with audience RegisterAccount and your email address in the JWT. Your email address also gets put into the query string of the redirect URL, which is used to pre-populate the form. When registration is complete, the email address of the logged-in user (the RegisterAccount JWT) is compared to the email address in the submitted form; if they're the same, i.e. the user didn't change the email field of the form, then email verification is not required. However, if the user did change the email address in the form, we require email verification because we don't know that they control that *other* email address they just typed in.

**Comment by rmunn** [comment]
Actually, I just confirmed via testing on `localhost` that this isn't working as designed. Probably has something to do with the audience of the JWT, but I haven't dug down deep enough yet to confirm that theory. At any rate, if you register via Google Login, then you still get the "Please verify your email" message — but as long as you haven't changed the email address in the register page, you shouldn't have to verify your email because we trust Google to know that it belongs to you.
